// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_DWTgzAagmByQlk4V5yvw9tB1-F5RyI',
    appId: '1:83047135976:web:1612a591e58f442d4e675d',
    messagingSenderId: '83047135976',
    projectId: 'ha-app-fdd4f',
    authDomain: 'ha-app-fdd4f.firebaseapp.com',
    storageBucket: 'ha-app-fdd4f.firebasestorage.app',
    measurementId: 'G-YT86W0FDP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuhtwbSpIo29ZQ8hw96V0Irwxd6nzVNQ',
    appId: '1:83047135976:android:b3c375851663248d4e675d',
    messagingSenderId: '83047135976',
    projectId: 'ha-app-fdd4f',
    storageBucket: 'ha-app-fdd4f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuV30IGzrWt_hNWM66Wn6bIRsnyUFfA9w',
    appId: '1:83047135976:ios:054f3f6c42fa71ea4e675d',
    messagingSenderId: '83047135976',
    projectId: 'ha-app-fdd4f',
    storageBucket: 'ha-app-fdd4f.firebasestorage.app',
    androidClientId: '83047135976-2hdhbfnafafa068pdup4lr84bvlt875a.apps.googleusercontent.com',
    iosClientId: '83047135976-9gucbvtuosgrc6fhp10ulm55idcr3opp.apps.googleusercontent.com',
    iosBundleId: 'com.example.haEcommerce',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuV30IGzrWt_hNWM66Wn6bIRsnyUFfA9w',
    appId: '1:83047135976:ios:054f3f6c42fa71ea4e675d',
    messagingSenderId: '83047135976',
    projectId: 'ha-app-fdd4f',
    storageBucket: 'ha-app-fdd4f.firebasestorage.app',
    androidClientId: '83047135976-2hdhbfnafafa068pdup4lr84bvlt875a.apps.googleusercontent.com',
    iosClientId: '83047135976-9gucbvtuosgrc6fhp10ulm55idcr3opp.apps.googleusercontent.com',
    iosBundleId: 'com.example.haEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-_DWTgzAagmByQlk4V5yvw9tB1-F5RyI',
    appId: '1:83047135976:web:906b88f24e266d0b4e675d',
    messagingSenderId: '83047135976',
    projectId: 'ha-app-fdd4f',
    authDomain: 'ha-app-fdd4f.firebaseapp.com',
    storageBucket: 'ha-app-fdd4f.firebasestorage.app',
    measurementId: 'G-LJJLJF0490',
  );
}
